### ISSUE TITLE
[GCC] PAD: SST - Investigar o sst_update (name_list)

### ISSUE THREAD

**Issue by joaomas** [monanadmin/monan#416]
## :people_holding_hands: User Story

COMO Saulo,
QUEREMOS iniciar o processo de testes contínuos do MONAN-MPAS começando pelas condições iniciais,
PARA melhor avaliação do modelo e uso do Egeon.

## :clipboard: Critérios de aceite de conclusão da Issue

- [x] Investigar o sst_update (name_list) (e.g. é apenas output?)

## :pencil: Detalhamento adicional da atividade

_(... espaço para detalhar melhor o que deve ser realizado)_

## :comet: Impactos

_(... consequência técnica encontrada durante a execução da issue)_

## :link: Dependências

_(... issues e requisitos que devem ser executados previamente)_

## :hammer_and_wrench: Solução

Informações complementares na #414 .

### Conversamos com o Pablo:

- Segundo o manual do MPAS, rodadas para até 7 dias os campos de SST não são atualizados, as simulações usam a sst da CI. Para rodadas maiores que 7 dias, existe a opção do modelo atualizar os campos de SST periodicamente através dos passos descritos no manual (Seção 8.2.2).
- Para previsões de caráter de tempo, o impacto da atualização da SST nas previsões (de curto prazo) são ínfimas (pois as previsões estão muito próximas da CI). Atualizações periódicas de SST são mais utilizadas em previsões sazonais.
- Importante considerar informações desta apresentação  https://www2.mmm.ucar.edu/projects/mpas/tutorial/Virtual2023/lectures/Running_part_1_ICs.pdf (a partir do slide 27) para alterar os arquivos `namelist.init_atmosphere` e `streams.init_atmosphere`;
- Para gerar campos de SST para serem lidos pelo modelo periodicamente (separadamente dos campos da CI), é necessário executar o `degrib.exe` também separadamente, seguindo os passos abaixo:

Passos:
1. Obter arquivos de sst em `/oper/dados/ioper/tempo/NCEP/input/2024/01/10/00/rtgssthr_grb_0.083.grib2.20240110`;
2. Obter `Vtable` para a o arquivo de SST (https://github.com/wrf-model/WPS/blob/master/ungrib/Variable_Tables/Vtable.SST [EGK: após encontrar esse git, atentar quanto a versão da branch/tag utilizada]);
3. Seguir os passos para usar o `degrib.exe` e gerar um arquivo de SST (segundo procedimentos da https://www2.mmm.ucar.edu/projects/mpas/tutorial/Virtual2023/ item 2.2);
OBS: Importante neste passo alterar o `namelist.wps`: 
> out_format = 'SST',
> start_date = '#LABELI#',
> end_date   = '#LABELF#',

4.  É possível editar o Vtable através do procedimento encontrado em:
https://www2.mmm.ucar.edu/wrf/users/docs/user_guide_v4/v4.0/users_guide_chap3.html#_Creating_and_Editing_1
  

------

## :rotating_light: Problemas encontrados

N.A.

## :white_check_mark: Conclusão

Das inforações coletas cobriram 90% aproximadamente do passo-a-passo necessário para compor todo o processo.
A flag `sst_update`, segundo informações, serve para indicar que a simulação atualizará os campos de sst periodicamente por todo o horizonte de previsão.

## :spiral_calendar: Trabalhos Futuros

_(... caso a issue demande trabalhos futuros detalhar aqui e marcar o campo "Future Work" ao lado para "Sim")_

**Comment by deniseiras** [comment]
Links:
[Manual do MPAS](https://www2.mmm.ucar.edu/projects/mpas/mpas_atmosphere_users_guide_8.0.1.pdf)

[Apresentação ICS](https://www2.mmm.ucar.edu/projects/mpas/tutorial/Virtual2023/lectures/Running_part_1_ICs.pdf)

**Comment by egkhamis** [comment]
Informações sobre o formato do arquivo intermediário [fonte: https://www2.mmm.ucar.edu/wrf/OnLineTutorial/Basics/IM_files/index.php]:

"Fields are written to the intermediate files as 2–dimensional horizontal slabs of data. Each horizontal slab contains a single level of a single variable (i.e., 500 mb RH, surface T, etc.). Any number of horizontal slabs may be written to a single file. The slabs in a given file are not necessarily all from the same data source, or all on the same grid or map projection, but they should all represent the data valid at the same time.

Each file contains data for a single time. The file names consist of a prefex (ideally, but not necessarily, denoting the source of data), followed by a colon, followed by a time–stamp in the form YYYY–MM–DD_HH.

The files are written as unformatted FORTRAN records. For each horizontal data slab a number of records are written. The number of records depends on the intermediate file version. Typical information in these records is:

– A version number
– Information common to all types of gridded data
– Information specific to the particular grid type represented
– A 2–dimensional slab of data
The intermediate file format was originally developed for the MM5 model. Due to its easy use, this file format has been passed on to the WRF modeling system. To fulfill extra requirements, various versions of this format are currently in use. The WPS package can read all the different versions, so users with older intermediate file formats can still use this data as input to the WPS. A switch in the namelist.wps file (out_format) gives users control over the version they are using as input."
